"""changed null contraints

Revision ID: 56b69ede8cca
Revises: 55851e1080b3
Create Date: 2024-03-05 18:20:12.727981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56b69ede8cca'
down_revision: Union[str, None] = '55851e1080b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('collection_dynamic', 'total_average_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('collection_dynamic', 'total_supply',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('collection_dynamic', 'total_volume',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('collection_dynamic', 'total_num_owners',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('collection_dynamic', 'total_sales',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('collection_dynamic', 'total_market_cap',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('collection_dynamic', 'sales',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('collection_dynamic', 'volume',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('collection_dynamic', 'floor_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('collection_dynamic', 'floor_price_currency',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('collection_dynamic', 'average_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.drop_column('nft_listing', 'buyer')
    op.drop_column('nft_transfer', 'price_val')
    op.drop_column('nft_transfer', 'price_currnecy')
    op.drop_column('nft_transfer', 'price_symbol')
    op.add_column('payment_tokens', sa.Column('chain', sa.String(), nullable=False))
    op.alter_column('payment_tokens', 'symbol',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payment_tokens', 'symbol',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('payment_tokens', 'chain')
    op.add_column('nft_transfer', sa.Column('price_symbol', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('nft_transfer', sa.Column('price_currnecy', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('nft_transfer', sa.Column('price_val', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('nft_listing', sa.Column('buyer', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.alter_column('collection_dynamic', 'average_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('collection_dynamic', 'floor_price_currency',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('collection_dynamic', 'floor_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('collection_dynamic', 'volume',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('collection_dynamic', 'sales',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('collection_dynamic', 'total_market_cap',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('collection_dynamic', 'total_sales',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('collection_dynamic', 'total_num_owners',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('collection_dynamic', 'total_volume',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('collection_dynamic', 'total_supply',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('collection_dynamic', 'total_average_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    # ### end Alembic commands ###
