services:
  db:
    image: timescale/timescaledb:latest-pg14
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - db-data:/var/lib/postgresql/data

  api:
    build:
      context: .
      target: dev-envs
    container_name: vplay-backend
    environment:
      PORT: 8000
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    env_file:
      - .env
    ports:
      - '8000:8000'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./app:/app
    restart: 'no'
    depends_on:
      - db

volumes:
  db-data:
