"""added updated_at columns

Revision ID: 1c3694ec1acc
Revises: 56b69ede8cca
Create Date: 2024-03-05 19:45:06.304823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c3694ec1acc'
down_revision: Union[str, None] = '56b69ede8cca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collection', sa.Column('updated_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('collection', 'updated_at')
    # ### end Alembic commands ###
